Repository avh4/elm-format, pull requests merged in 2019-08, with the labels that each got.

#623 JSON type annotations
  parser/src/AST/Declaration.hs
  parser/src/AST/Json.hs
  parser/src/AST/Pattern.hs
  parser/src/AST/V0_16.hs
  parser/src/Parse/Comments.hs
  parser/src/Parse/Helpers.hs
  parser/src/Parse/Type.hs
  parser/src/Reporting/Annotation.hs
  src/AST/MapExpr.hs
  src/AST/MapNamespace.hs
  src/ElmFormat/Render/Box.hs
  src/ElmFormat/Upgrade_0_19.hs
  tests/test-files/good/Elm-0.18/AllSyntax/Expressions.json
  tests/test-files/good/Elm-0.18/AllSyntax/Literals.json
  tests/test-files/good/Elm-0.18/AllSyntax/Module.json
  tests/test-files/good/json/ExternalReferences.json
Labels: public AST

#625 `module` lines with no `exposing` clause will have the clause automatically generated
  CHANGELOG.md
  parser/src/AST/Module.hs
  parser/src/Parse/Module.hs
  src/ElmFormat/Render/Box.hs
  tests/Test/Generators.hs
  tests/test-files/transform/Elm-0.19/ListAllExportsNoExposing.elm
  tests/test-files/transform/Elm-0.19/ListAllExportsNoExposing.formatted.elm
  tests/test-files/transform/Elm-0.19/ListAllExportsNoModuleLine.elm
  tests/test-files/transform/Elm-0.19/ListAllExportsNoModuleLine.formatted.elm
  tests/test-files/transform/Elm-0.19/ListDocumentedExportsNoExposing.elm
  tests/test-files/transform/Elm-0.19/ListDocumentedExportsNoExposing.formatted.elm
Labels: lenient parser

#597 Update and clarify VSCode installation instructions.
  README.md
Labels: documentation

#627 Jetbrains update
  README.md
  img/JetBrains setup.png
Labels: documentation

#488 Change JetBrains plugin
  README.md
  img/JetBrains setup.png
Labels: documentation
