Repository avh4/elm-format, pull requests merged in 2020-09, with the labels that each got.

#691 in doc comments, inline code containing backticks is now escaped corr…
  CHANGELOG.md
  elm-format.cabal
  src/Data/Text/Extra.hs
  src/ElmFormat/Render/Markdown.hs
  tests/Data/Text/ExtraTest.hs
  tests/Test.hs
  tests/test-files/good/Elm-0.18/AllSyntax/DocComments.elm
Labels: bug

#700 Safe autolinks
  CHANGELOG.md
  README.md
  elm-format.cabal
  src/ElmFormat/Render/Markdown.hs
  src/Regex.hs
  tests/test-files/good/Elm-0.18/AllSyntax/DocComments.elm
Labels: bug

#704 package with shake
  .github/workflows/Build release.yml
  .github/workflows/CI.yml
  .gitignore
  Dockerfile
  Shakefile.hs
  Style Guide/CI.md
  markdown/Cheapskate/ParserCombinators.hs
  src/Flags.hs
  src/Regex.hs
  stack.yaml
Labels: packaging

#678 VSCode elm language support is deprecated
  README.md
Labels: documentation

#711 Build static linux binary
  .dockerignore
  CHANGELOG.md
  Dockerfile
  Shakefile.hs
  package/linux/build-in-docker.sh
Labels: packaging, platform: Linux
