Repository avh4/elm-format, pull requests merged in 2023-03, with the labels that each got.

#802 Update to hspec-golden 0.2.0.0
  cabal.project.freeze
  default.nix
  elm-format-test-lib/elm-format-test-lib.cabal
  elm-format-test-lib/src/CommandLine/TestWorld.hs
Labels: maintenance

#803 Use hpack
  .github/actions/haskell/action.yml
  README.md
  Shakefile/build-elm-format.cabal
  Shakefile/package.yaml
  avh4-lib/avh4-lib.cabal
  avh4-lib/package.yaml
  dev/build.sh
  elm-format-lib/elm-format-lib.cabal
  elm-format-lib/package.yaml
  elm-format-markdown/elm-format-markdown.cabal
  elm-format-markdown/package.yaml
  elm-format-test-lib/elm-format-test-lib.cabal
  elm-format-test-lib/package.yaml
  elm-format.cabal
  package.yaml
  shell.nix
Labels: maintenance

#806 Transform `case .. then` into `case .. of` (lenient-parser) 🛠
  CHANGELOG.md
  LICENSE
  elm-format-lib/src/Parse/Expression.hs
  tests/test-files/transform/Elm-0.19/ReplaceThenByOfInCase.elm
  tests/test-files/transform/Elm-0.19/ReplaceThenByOfInCase.formatted.elm
Labels: lenient parser

#807 Allow use of "infix" everywhere Elm 0.19 allows it
  CHANGELOG.md
  elm-format-lib/src/Parse/Declaration.hs
  tests/test-files/good/Elm-0.19/InfixAsVariableName.elm
Labels: bug

#808 Generate coverage reports
  .gitignore
  README.md
  Shakefile/build-elm-format.cabal
  Shakefile/src/Main.hs
  Shakefile/src/Shakefiles/ElmFormat/IntegrationTests.hs
  Shakefile/src/Shakefiles/Haskell.hs
  Shakefile/src/Shakefiles/Haskell/Hpc.hs
  Shakefile/src/Shakefiles/ListFiles.hs
  Shakefile/src/Shakefiles/Prelude.hs
  dev/Documentation/Build Commands.md
  shell.nix
Labels: maintenance

#809 Transform `=>` into `->` (lenient-parser) 🏹
  CHANGELOG.md
  elm-format-lib/src/Parse/Helpers.hs
  tests/test-files/transform/Elm-0.19/TransformFatArrow.elm
  tests/test-files/transform/Elm-0.19/TransformFatArrow.formatted.elm
Labels: feature for developers
