Repository avh4/elm-format, pull requests merged in 2023-02, with the labels that each got.

#784 Configure MacOS ARM64 release builds
  .github/workflows/Build release (lamdera-community).yml
  .github/workflows/Build release.yml
  .github/workflows/CI.yml
  .github/workflows/Snapshot release.yml
  Shakefiles/Haskell.hs
  Shakefiles/Platform.hs
  shell.nix
Labels: packaging, platform: Mac, maintenance

#769 Add macos aarch64 build support to Shakefile system
  Shakefiles/Dependencies.hs
  Shakefiles/Extra.hs
  Shakefiles/Haskell.hs
  Shakefiles/Platform.hs
  build.sh
Labels: packaging, platform: Mac

#785 Allow bimap 0.5.*
  avh4-lib/avh4-lib.cabal
  cabal.project.freeze
  elm-format-lib/elm-format-lib.cabal
  elm-format.cabal
Labels: maintenance

#786 Update dev scripts
  .github/workflows/Build release (lamdera-community).yml
  .github/workflows/Build release.yml
  .github/workflows/CI.yml
  .github/workflows/Snapshot release.yml
  .github/workflows/Touch cache.yml
  .gitpod.yml
  .hlint.yaml
  HLint.hs
  PUBLISHING.md
  README.md
  Shakefile/build-elm-format.cabal
  Shakefile/src/Main.hs
  Shakefile/src/Shakefiles/Dependencies.hs
  Shakefile/src/Shakefiles/Extra.hs
  Shakefile/src/Shakefiles/Haskell.hs
  Shakefile/src/Shakefiles/Platform.hs
  Shakefile/src/Shakefiles/Shellcheck.hs
  Shakefile/src/Shakefiles/Signature.hs
  build.sh
  cabal.project
  cabal.project.freeze
  dev/build.sh
  elm-format-lib/src/Reporting/Error/Helpers.hs
  hie.yaml
  package/linux/build-package.sh
  package/mac/build-package.sh
  package/win/build-package.sh
  tests/Integration/CliTest.hs
Labels: maintenance

#790 Upgrade to optparse-applicative 0.17.0.0
  cabal.project.freeze
  elm-format-lib/elm-format-lib.cabal
  elm-format.cabal
  tests/usage.stdout/golden
Labels: maintenance

#791 Fix GitHub CI caching
  .github/actions/cache-build/action.yml
  .github/actions/cache-haskell-deps/action.yml
  .github/actions/git-tags/action.yml
  .github/actions/haskell/action.yml
  .github/actions/release-artifact/action.yml
  .github/workflows/Build release (lamdera-community).yml
  .github/workflows/Build release.yml
  .github/workflows/CI.yml
  .github/workflows/Snapshot release.yml
  .github/workflows/Touch cache.yml
Labels: maintenance

#795 Automate the new npm packages
  .github/workflows/Check published packages (nixpkgs).yml
  .github/workflows/Check published packages (npm).yml
  PUBLISHING.md
  package/npm/.gitignore
  package/npm/base-package.nix
  package/npm/bin/elm-format
  package/npm/binary-package.nix
  package/npm/binary.js
  package/npm/default.nix
  package/npm/elm-format-0.8.5-test.nix
  package/npm/index.js
  package/npm/package.json
  package/npm/platform-info.nix
  package/npm/shell.nix
  package/npm/workspace.nix
  shell.nix
Labels: packaging, in-progress

#798 Scripts for packaging linux-aarch64
  .gitignore
  Shakefile/build-elm-format.cabal
  Shakefile/src/Main.hs
  Shakefile/src/Shakefiles/ElmFormat/IntegrationTests.hs
  Shakefile/src/Shakefiles/Haskell.hs
  Shakefile/src/Shakefiles/NestedCheckout.hs
  Shakefile/src/Shakefiles/NixBuild.hs
  avh4-lib/LICENSE
  avh4-lib/avh4-lib.cabal
  default.nix
  elm-format-lib/LICENSE
  elm-format-lib/elm-format-lib.cabal
  elm-format-test-lib/LICENSE
  elm-format-test-lib/elm-format-test-lib.cabal
  elm-format.cabal
  nix/sources.json
  shell.nix
Labels: packaging, platform: Linux
